version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PGHOST=db
      - PGUSER=nodepg
      - PGDATABASE=postgres
      - PGPASSWORD=nodepgpw
      - PGPORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=nodepg
      - POSTGRES_PASSWORD=nodepgpw
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d

volumes:
  pgdata:
